Modify sync so that it syncs all gardens even if one has an issue.

diff --git a/bin/sync b/bin/sync
--- a/bin/sync
+++ b/bin/sync
@@ -6,6 +6,8 @@ git pull
 cd $HOME/agora/garden
 for i in *; do
     cd $i
-    git pull
+    echo "*** pulling $i"
+    git pull || echo "error pulling"
+    echo "*** finished pulling $i"
     cd ..
 done
